import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import type { Metadata } from 'next';
// import { Open_Sans } from 'next/font/google';
// const inter = Open_Sans({
//   weight: ['300', '400', '500', '600', '800']
//   })

export const metadata: Metadata = {
  title: 'Bespoke',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
